create or replace PROCEDURE "LOAD_ETL_PARAMETERS" 
(TABLE_NAME IN VARCHAR2, CODE IN VARCHAR2,TASK_RUN_KEY OUT VARCHAR2, MAX_LOAD_DATE OUT DATE, START_TIME OUT TIMESTAMP, 
END_TIME OUT TIMESTAMP, DURATION OUT INTEGER, NO_OF_INSERTS OUT INTEGER, 
STATUS OUT VARCHAR2, ERROR_MESSAGE OUT VARCHAR2, TABLE_OUT OUT VARCHAR2 , CODE_OUT OUT VARCHAR2) 
is
begin
SELECT TABLE_NAME, CODE into TABLE_OUT,CODE_OUT from dual;
END LOAD_ETL_PARAMETERS_V2;
