CREATE OR REPLACE PROCEDURE "ADMIN"."LOAD_ETL_PARAMETERS" 
(SOURCE IN VARCHAR2, TABLE_NAME IN VARCHAR2, MAX_LOAD_DATE OUT DATE) IS v_MAX_LOAD_DATE date; 

BEGIN EXECUTE IMMEDIATE 'SELECT MAX(trunc(LAST_LOAD_DATE)) from MANAGE_ETL where SOURCE = ' || '''' || 
SOURCE || '''' || ' AND TABLE_NAME = ' || '''' || TABLE_NAME || '''' 
into MAX_LOAD_DATE; 

END LOAD_ETL_PARAMETERS;	
